### ISSUE TITLE
Intel Cpu Core 13 Bug

### ISSUE THREAD

**Issue by cicin411** [Lexikos/AutoHotkey-Release#12]
version: ahk v2 newest
system: win11
cpu: Intel Core 13 / 12 (Heterogeneous processors with a mix of large and small cores）
Problem Description：
using hotkey as below   (default key-send-mode)
j::send("{left}")  
and then hold on j  key.
we expect:
"left  left left left left left left......"
what happens in fact:
"left left....(several)...  j.....left left......j......"
j key is sent from time to time during the  left key sending.

I test it with amd cpu (no mixture with large and small cores),  thing goes well, no bug.

and

I test it when changing key-send-mode from default to "SendEvent", thing goes well too, no bug.

**Comment by Lexikos** [comment]
Refer [[v2] Intel Cpu Core 13 Bug - AutoHotkey Community](https://www.autohotkey.com/boards/viewtopic.php?f=14&t=118767).

Even if this was a bug in the program, this repository is for the release script, not AutoHotkey itself.
> Release script for AutoHotkey. Builds the binaries, help file and installer, and automates other release steps.
