### ISSUE TITLE
Can't install autohotkey

### ISSUE THREAD

**Issue by brian2lee** [Lexikos/AutoHotkey-Release#13]
I've tried many ways to install autohotkey, always ran into errors.(I know it's kinda weird to ask it here but I couldn't find issue thread in the official [git](https://github.com/AutoHotkey/AutoHotkey/releases).)

> Installing from AutoHotkey_2.0.11_setup.exe

```
	294: NumPut("ushort", NumGet(endTime, "ushort") + 10, endTime)
	295: If !hCert := DllCall("Crypt32\CertCreateSelfSignCertificate" , "ptr", prov, "ptr", cnb, "uint", 0, "ptr", 0 , "ptr", 0, "ptr", 0, "ptr", endTime, "ptr", 0, "ptr")
▶	298: Throw OSError()
	299: cert := CertContext(hCert)
	300: If !DllCall("Crypt32\CertAddCertificateContextToStore", "ptr", hStore , "ptr", hCert, "uint", 1, "ptr", 0)

The current thread will exit.

Call stack:
*#1 (298) : [EnableUIAccess_CreateCert] Throw OSError()
*#1 (218) : [EnableUIAccess] cert := EnableUIAccess_CreateCert(CertName, hStore)
*#1 (1096) : [Installation.Prototype.MakeUIA] EnableUIAccess(newPath)
*#1 (527) : [Installation.Prototype.Apply] item(this)
*#1 (587) : [Installation.Prototype.InstallFull] this.Apply()
*#1 (412) : [Install_Main] inst.%method%(params*)
*#1 (1200) : [] Install_Main()
> Auto-execute
```
> AutoHotkey_1.1.37.01_setup.exe
> Stuck at installing "this shouldn't take long"

> AutoHotkey_1.1.37.01.zip & AutoHotkey_2.0.11.zip
> Run Script won't work

**Comment by Lexikos** [comment]
AutoHotkey/AutoHotkeyUX@306434b9 fixes this for v2.0.12 and later versions. All prior versions will continue to fail in this way on Febrary 29th.
