### ISSUE TITLE
The alt key runs automatically out of control

### ISSUE THREAD

**Issue by grantsimongrant** [Lexikos/AutoHotkey-Release#16]
I made several shortcut mappings related to the alt key, but ahk doesn't always run smoothly. 
When the ahk script is running, the alt key runs automatically out of control.
This makes me feel really bad at programming, I hope I can get some answers or help from you.
Thank you for listening!
![alt](https://github.com/Lexikos/AutoHotkey-Release/assets/47892240/28ccd502-12e3-4e45-9f87-d9bf80937098)

**Comment by grantsimongrant** [comment]
> 我做了几个与 alt 键相关的快捷方式映射，但 ahk 并不总是运行流畅。当 ahk 脚本运行时，alt 键会自动失控运行。这让我在编程方面感觉很糟糕，我希望我能从你那里得到一些答案或帮助。感谢您的聆听！ ![alt](https://private-user-images.githubusercontent.com/47892240/335186784-28ccd502-12e3-4e45-9f87-d9bf80937098.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwNzM5ODAsIm5iZiI6MTcxNzA3MzY4MCwicGF0aCI6Ii80Nzg5MjI0MC8zMzUxODY3ODQtMjhjY2Q1MDItMTJlMy00ZTQ1LTlmODctZDliZjgwOTM3MDk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTMwVDEyNTQ0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYzNTg1ODMwMTg2NDk0YzY3MDEwNjRiNjZhMTgzMDQ0YzhhY2U4NDA2Y2Y1YzI2OTljODZjOTkxMmQxMzgyZGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6aIWdSwfQSYIItxR5clIFh81aE6dquIuTANWca3ENeI)

Additionaly, there's nothing wrong with my keyboard

**Comment by Lexikos** [comment]
This repository is for scripts which automate the release of AutoHotkey. It is not a support forum.

If you want help, I would advise that you post on the [community forums](https://www.autohotkey.com/boards/), in the Ask for Help subforum appropriate for whichever AutoHotkey version you are using. Include essential details, such as what code you are using, what effect it is having, and what effect you want it to have.
