### ISSUE TITLE
Hotkeys dont type all Characters?

### ISSUE THREAD

**Issue by Ferynix** [Lexikos/AutoHotkey-Release#5]
I was using the hotkeys and I tried using
`NUMPAD1::
Send, /say{space}
Send, EXAMPLETEST
Return` and It worked, but it keeps writing it as "/ay EXAMPLETEST" or "/y EXAMPLETEST" I need it to say the entire /say command....

I attached Below a version that half worked for me, but its just making it slightly faster...
[Exmaple.zip](https://github.com/Lexikos/AutoHotkey-Release/files/3145997/Exmaple.zip)

**Comment by safetycar** [comment]
Some info about the program where you're typing could be relevant.

**Comment by Lexikos** [comment]
Pleases pay attention to where you are. This repository is for:
> Release script for AutoHotkey. Builds the binaries, help file and installer, and automates other release steps.

For general AutoHotkey support, use the [forum](https://www.autohotkey.com/boards/). I think your issue can probably be solved by following the directions in the [games FAQ](https://autohotkey.com/docs/FAQ.htm#games), although the question doesn't exactly match.
